In [1]:
import pandas as pd
import numpy as np

In [4]:
# read tsv
df5comb = pd.read_csv('doi_10_5061_dryad_sm847__v20181016/db_drugs_5s.tsv', sep='\t')
df4comb = pd.read_csv('doi_10_5061_dryad_sm847__v20181016/db_drugs_4s.tsv', sep='\t')
df3comb = pd.read_csv('doi_10_5061_dryad_sm847__v20181016/db_drugs_3s.tsv', sep='\t')

,drug_name_A,drug_name_B,drug_name_C,atleast_exposure_count,exact_exposure_count,estimate_drug_cost_per_day,fraction_exact,fraction_allwindows,observe_per_expect_1s,observe_per_expect_N1
0,hydrochlorothiazide,hydrocodone,acetaminophen,9973460,54353,3.62,0.0054,0.0059,13.352,1.027
1,hydrochlorothiazide,lisinopril,simvastatin,9379261,1151294,1.89,0.1227,0.0055,6.900,2.214
2,hydrochlorothiazide,lisinopril,metformin,8285899,331146,2.17,0.04,0.0049,8.510,2.730
3,hydrocodone,lisinopril,acetaminophen,7846241,139073,3.04,0.0177,0.0046,14.636,1.125
4,hydrocodone,acetaminophen,thyroxine,7128884,196806,3.14,0.0276,0.0042,12.540,0.964
...,...,...,...,...,...,...,...,...,...,...
77929,ergocalciferol,sertraline,valsartan,10002,142,3.74,0.0142,0.0000,0.806,0.534
77930,alprazolam,valsartan,glyburide,10002,<100,3.98,,0.0000,1.020,0.397
77931,ezetimibe,venlafaxine,warfarin,10002,<100,7.02,,0.0000,1.219,0.494
77932,esomeprazole,hydroxychloroquine,tramadol,10001,208,7.54,0.0208,0.0000,3.838,0.941
77933,metoprolol,omeprazole,butalbital,10001,<100,3.84,,0.0000,0.681,0.373

In [6]:
# get drug_name_A, drug_name_B, and drug_name_C to create a new column
# array 
df5comb['drug_names'] = df5comb[['drug_name_A', 'drug_name_B', 'drug_name_C', 'drug_name_D', 'drug_name_E']].values.tolist()
df4comb['drug_names'] = df4comb[['drug_name_A', 'drug_name_B', 'drug_name_C', 'drug_name_D']].values.tolist()
df3comb['drug_names'] = df3comb[['drug_name_A', 'drug_name_B', 'drug_name_C']].values.tolist()

# concat all the datasets to one (before it, get only drug_names, exact_exposure_count, atleast_exposure_count columns
df5comb = df5comb[['drug_names', 'exact_exposure_count', 'atleast_exposure_count']]
df4comb = df4comb[['drug_names', 'exact_exposure_count', 'atleast_exposure_count']]
df3comb = df3comb[['drug_names', 'exact_exposure_count', 'atleast_exposure_count']]

dfcomb = pd.concat([df5comb, df4comb, df3comb])

In [7]:
dfcomb

,drug_names,exact_exposure_count,atleast_exposure_count
0,"[hydrocodone, salmeterol, acetaminophen, albut...",8371,498823
1,"[hydrochlorothiazide, hydrocodone, lisinopril,...",13485,491033
2,"[hydrochlorothiazide, hydrocodone, lisinopril,...",4655,457284
3,"[hydrocodone, lisinopril, metformin, simvastat...",4201,364017
4,"[hydrochlorothiazide, lisinopril, metformin, m...",18768,345378
...,...,...,...
77929,"[ergocalciferol, sertraline, valsartan]",142,10002
77930,"[alprazolam, valsartan, glyburide]",<100,10002
77931,"[ezetimibe, venlafaxine, warfarin]",<100,10002
77932,"[esomeprazole, hydroxychloroquine, tramadol]",208,10001
77933,"[metoprolol, omeprazole, butalbital]",<100,10001

In [29]:
# get most common 40 drugs
most40common = dfcomb['drug_names'].explode().value_counts().head(100).index.tolist()
most40common

['hydrochlorothiazide',
 'metformin',
 'simvastatin',
 'lisinopril',
 'acetaminophen',
 'amlodipine',
 'metoprolol',
 'thyroxine',
 'atorvastatin',
 'hydrocodone',
 'furosemide',
 'omeprazole',
 'fluticasone',
 'clopidogrel',
 'ezetimibe',
 'atenolol',
 'losartan',
 'zolpidem',
 'valsartan',
 'fenofibrate',
 'esomeprazole',
 'gabapentin',
 'albuterol',
 'alprazolam',
 'pioglitazone',
 'salmeterol',
 'montelukast',
 'carvedilol',
 'warfarin',
 'rosuvastatin',
 'insulin glargine',
 'glipizide',
 'sitagliptin',
 'triamterene',
 'sertraline',
 'benazepril',
 'oxycodone',
 'pravastatin',
 'prednisone',
 'bupropion',
 'allopurinol',
 'pantoprazole',
 'amoxicillin',
 'tramadol',
 'glimepiride',
 'tamsulosin',
 'citalopram',
 'diltiazem',
 'escitalopram',
 'glyburide',
 'azithromycin',
 'duloxetine',
 'ethinyl estradiol',
 'cyclobenzaprine',
 'meloxicam',
 'clonazepam',
 'fluoxetine',
 'trazodone',
 'lorazepam',
 'olmesartan',
 'estradiol',
 'digoxin',
 'isosorbide',
 'venlafaxine',
 'celecoxib',
 'spironolactone',
 'ramipril',
 'fexofenadine',
 'codeine',
 'lansoprazole',
 'estrogens, conjugated (usp)',
 'clonidine',
 'lovastatin',
 'alendronate',
 'tiotropium',
 'ibuprofen',
 'amitriptyline',
 'ciprofloxacin',
 'paroxetine',
 'enalapril',
 'promethazine',
 'mometasone',
 'pregabalin',
 'ergocalciferol',
 'verapamil',
 'irbesartan',
 'clavulanate',
 'trimethoprim',
 'omega-3 acid ethyl esters (usp)',
 'naproxen',
 'diclofenac',
 'insulin, aspart, human',
 'norethindrone',
 'quinapril',
 'ranitidine',
 'dextroamphetamine',
 'sulfamethoxazole',
 'ipratropium',
 'amphetamine',
 'nifedipine']

In [15]:
# filter so that drug_names array always contains all the drugs from most40common
# dfcomb_filter40 = dfcomb[dfcomb['drug_names'].apply(lambda x: all(i in x for i in most40common))]

In [16]:
# dfcomb_filter40

Empty DataFrame
Columns: [drug_names, exact_exposure_count, atleast_exposure_count]
Index: []

In [17]:
dfcomb['drug_names'].apply(lambda x: all(i in x for i in most40common))

0        False
1        False
2        False
3        False
4        False
         ...
77929    False
77930    False
77931    False
77932    False
77933    False
Name: drug_names, Length: 151746, dtype: bool

In [27]:
# filter each drug_names array so that it contains only the most common 40 drugs
dfcomb_filter40 = dfcomb.copy()
dfcomb_filter40['drug_names'] = dfcomb_filter40['drug_names'].apply(lambda x: [i for i in x if i in most40common])
dfcomb_filter40 = dfcomb_filter40[dfcomb_filter40['drug_names'].apply(lambda x: len(x) >= 3)]

In [28]:
dfcomb_filter40['drug_names']

0        [hydrocodone, salmeterol, acetaminophen, albut...
1        [hydrochlorothiazide, hydrocodone, lisinopril,...
2        [hydrochlorothiazide, hydrocodone, lisinopril,...
3        [hydrocodone, lisinopril, metformin, simvastat...
4        [hydrochlorothiazide, lisinopril, metformin, m...
                               ...
77924                 [esomeprazole, lovastatin, zolpidem]
77925                    [lovastatin, verapamil, warfarin]
77929              [ergocalciferol, sertraline, valsartan]
77930                   [alprazolam, valsartan, glyburide]
77931                   [ezetimibe, venlafaxine, warfarin]
Name: drug_names, Length: 124576, dtype: object